### ISSUE TITLE
Create read/write stream that starts/ends with custom index

### ISSUE THREAD

**Issue by pedromsilvapt** [feross/chunk-store-stream#7]
It would be really neat if we could specify which chunk index to start/stop reading. Even better would be to say the position (not chunk index, but byte index), and then we could calculate the closest index and discard any bytes before streaming to the client what was requested, although this could be done outside the library.

**Comment by feross** [comment]
Sure, I am open to this idea. But I can't implement it for you -- really busy right now. PR welcome!
